/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author serge
 */
public class ViewImg extends javax.swing.JFrame {

    /**
     * Creates new form ViewImg
     */
    public ViewImg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRetroceder = new javax.swing.JButton();
        LabelBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRetroceder.setBackground(new java.awt.Color(37, 37, 37));
        BtnRetroceder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetroceder.setText("Atrás");
        BtnRetroceder.setFocusable(false);
        BtnRetroceder.setMaximumSize(new java.awt.Dimension(100, 50));
        BtnRetroceder.setMinimumSize(new java.awt.Dimension(50, 50));
        BtnRetroceder.setPreferredSize(new java.awt.Dimension(100, 50));
        BtnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        LabelBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgApp.jpg"))); // NOI18N
        LabelBg.setMaximumSize(new java.awt.Dimension(500, 500));
        LabelBg.setMinimumSize(new java.awt.Dimension(500, 500));
        LabelBg.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(LabelBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetrocederActionPerformed
        Main mainInstance = Main.getIntanceMain();
        mainInstance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnRetrocederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewImg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewImg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewImg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewImg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewImg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRetroceder;
    private javax.swing.JLabel LabelBg;
    // End of variables declaration//GEN-END:variables
}
